Mention and Main Component
hatchways/team-cherry pull request #14
Opened 2020-06-30 18:23 UTC by powerseed

Developed Mention and Main Component with dummy content.

2020-06-30 19:30 UTC, grogsy approved these changes
checked out the UI, looks great!

2020-07-02 15:45 UTC, aeciorc requested changes

2020-07-02 15:45 UTC, aeciorc commented on client/package.json
> +    "fontsource-roboto": "^2.1.4",
The font roboto is already installed. Checkout index.html:
"    <link
      rel="stylesheet"
      type="text/css"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons"
    />"

2020-07-02 15:45 UTC, aeciorc commented on client/src/App.js
> +        <Route path="/landing" component={LandingPage} />
You can delete this component since we don't have a landing page

2020-07-02 15:45 UTC, aeciorc commented on client/src/Components/Header.js
> +    fontFamily: theme.typography.fontFamily,
You don't need this, actually. Because it's set on the theme.js, every typography will already have the fontFamily set there

2020-07-02 15:45 UTC, aeciorc commented on client/src/Components/Header.js
> +    background: theme.palette.primary.main,
Same for this. It will already use the palette for the theme primary color by default

2020-07-02 15:45 UTC, aeciorc commented on client/src/Components/Header.js
> +                <span style={{ color: "#191970" }}>crawler.</span>
Since we have a style object, I would just use className everywhere in this component, rather than inline.

2020-07-02 15:45 UTC, aeciorc commented on client/src/Components/Header.js
> +}
The navbar looks great 👍

2020-07-02 15:45 UTC, aeciorc commented on client/src/Components/Mention.js
> +import Grid from "@material-ui/core/Grid";
You can group these imports:
```js
import {
  Card,
  CardActionArea,
  CardContent,
  CardMedia,
  Typography,
  Grid,
} from "@material-ui/core";

```

2020-07-02 15:45 UTC, aeciorc commented on client/src/pages/Main.js
> +});
Same comment here as in Header.js

2020-07-02 15:45 UTC, aeciorc commented on client/src/pages/Main.js
> +                />
Try to make this a little flatter, and give the font more weight

2020-07-02 15:45 UTC, aeciorc commented on client/src/pages/Main.js
> +
Notice that the background in this page is actually a light shade of blue. You can use a color picker to get the exact tone rgb

2020-07-02 15:45 UTC, aeciorc commented on client/src/Components/Mention.js
> +    <Card style={{ height: "200px" }}>
Small improvement: Notice that the card has a shadow by default, but the one on the mockup doesn't

2020-07-02 18:38 UTC, powerseed commented
@aeciorc Fixed the issues you pointed out. Please review it. Thanks

2020-07-02 23:42 UTC, aeciorc approved these changes

2020-07-03 17:01 UTC, merged